export interface NodeInfo {
  id: string;
  title: string;
  description: string;
  whatItDoes?: string;
  connectedTo?: string;
  howItWorks?: string;
  category: string;
}

export const nodeData: Record<string, NodeInfo> = {
  AWS_ECS: {
    id: "AWS_ECS",
    title: "AWS Fargate/ECS",
    description: "Serverless compute engine for containers. Handles the core execution of trading algorithms and data processing tasks.",
    category: "Infrastructure",
  },
  AWS_RDS: {
    id: "AWS_RDS",
    title: "AWS RDS Postgres",
    description: "Relational database for storing structured data, including trade history and user profiles.",
    category: "Infrastructure",
  },
  AWS_Redis: {
    id: "AWS_Redis",
    title: "Redis ElastiCache",
    description: "In-memory data store for real-time state management and high-speed messaging.",
    category: "Infrastructure",
  },
  DF_Price: {
    id: "DF_Price",
    title: "Market Prices & Equities",
    description: "Real-time and historical price feeds for stocks and ETFs.",
    category: "Data Feeds",
  },
  DF_Macro: {
    id: "DF_Macro",
    title: "FRED Macro Economic Data",
    description: "Integration with Federal Reserve Economic Data (FRED) for macro indicators.",
    category: "Data Feeds",
  },
  DF_PMI: {
    id: "DF_PMI",
    title: "S&P Global PMI",
    description: "Purchasing Managers' Index data providing insights into sector health.",
    category: "Data Feeds",
  },
  DF_Crypto: {
    id: "DF_Crypto",
    title: "Crypto Microstructure",
    description: "Granular data on cryptocurrency order books and on-chain metrics.",
    category: "Data Feeds",
  },
  DF_VIX: {
    id: "DF_VIX",
    title: "VIX & Options Flow",
    description: "Volatility index data and real-time options market activity.",
    category: "Data Feeds",
  },
  L1_Pipeline: {
    id: "L1_Pipeline",
    title: "L1 Ingestion Pipeline",
    description: "The central aggregator that normalizes and cleans incoming data.",
    category: "Data Feeds",
  },
  Sim_Engine: {
    id: "Sim_Engine",
    title: "Historical Data Replay Engine",
    description: "Simulates past market conditions by feeding historical data into the pipeline.",
    category: "Simulation",
  },
  L2_Score: {
    id: "L2_Score",
    title: "Macro Regime Scoring",
    description: "Analyzes macro data to determine the current market 'regime'.",
    category: "Macro Compass",
  },
  L2_RPE: {
    id: "L2_RPE",
    title: "Regime Probability Engine",
    description: "Uses statistical models to forecast market regime transitions.",
    category: "Macro Compass",
  },
  L2_RSS: {
    id: "L2_RSS",
    title: "Retail Sentiment Score",
    description: "Monitors social sentiment to identify crowded trades.",
    category: "Macro Compass",
  },
  AI_Gateway: {
    id: "AI_Gateway",
    title: "LLM API Gateway",
    description: "Central interface for interacting with large language models (Gemini, Claude, GPT).",
    category: "Intelligence",
  },
  L3_SENTINEL: {
    id: "L3_SENTINEL",
    title: "SENTINEL",
    description: "A 6-gate entry validator that ensures all criteria are met before a trade.",
    category: "Risk & Conviction",
  },
  L3_TDC: {
    id: "L3_TDC",
    title: "Thesis Dependency Checker",
    description: "Continuously audits the original trade thesis against new data using AI.",
    category: "Risk & Conviction",
  },
  L3_CDM: {
    id: "L3_CDM",
    title: "Customer Dependency Map",
    description: "Maps supply chain relationships and alerts to event ripples.",
    category: "Risk & Conviction",
  },
  L3_MICS: {
    id: "L3_MICS",
    title: "Model-Implied Conviction Score",
    description: "Calculates the mathematical conviction level for a trade.",
    category: "Risk & Conviction",
  },
  L3_CDF: {
    id: "L3_CDF",
    title: "Conviction Decay Function",
    description: "Automatically reduces position size over time or if action stagnates.",
    category: "Risk & Conviction",
  },
  L3_CCM: {
    id: "L3_CCM",
    title: "Conviction Calibration",
    description: "A feedback loop that learns from past performance to adjust conviction logic.",
    category: "Risk & Conviction",
  },
  L3_TRP: {
    id: "L3_TRP",
    title: "Thesis Retirement Protocol",
    description: "Enforces disciplined exit logic when a thesis is no longer valid.",
    category: "Risk & Conviction",
  },
  L3_PTRH: {
    id: "L3_PTRH",
    title: "Permanent Tail Risk Hedge",
    description: "Automated insurance against extreme market crashes.",
    category: "Risk & Conviction",
  },
  L3_CAM: {
    id: "L3_CAM",
    title: "Coverage Adequacy Model",
    description: "Monitors whether current hedges are sufficient for the portfolio.",
    category: "Risk & Conviction",
  },
  L3_DSHP: {
    id: "L3_DSHP",
    title: "Defensive Sleeve Harvest",
    description: "Strategically sells safe-haven assets to raise cash during stress.",
    category: "Risk & Conviction",
  },
  L3_Safety: {
    id: "L3_Safety",
    title: "Incapacitation Protocol",
    description: "A 'dead-man's switch' that moves the portfolio to a safe state.",
    category: "Risk & Conviction",
  },
  L3_ARES: {
    id: "L3_ARES",
    title: "Re-Entry System",
    description: "Systematic protocol for buying back into high-conviction positions.",
    category: "Risk & Conviction",
  },
  L3_AUP: {
    id: "L3_AUP",
    title: "Asymmetric Upside Protocol",
    description: "Identifies and manages positions with massive potential upside.",
    category: "Risk & Conviction",
  },
  L4_Master: {
    id: "L4_Master",
    title: "Master Engine",
    description: "The core decision engine that combines all rules into a target portfolio.",
    category: "Execution",
  },
  L5_Orders: {
    id: "L5_Orders",
    title: "Order Book",
    description: "Calculates specific trades required to move to the target portfolio.",
    category: "Execution",
  },
  L6_Queue: {
    id: "L6_Queue",
    title: "Confirmation Queue",
    description: "A safety buffer where trades are held for final validation.",
    category: "Execution",
  },
  L6_Broker: {
    id: "L6_Broker",
    title: "Execution API",
    description: "The technical interface that submits orders to brokers.",
    category: "Execution",
  },
  L7_Log: {
    id: "L7_Log",
    title: "Immutable Session Log",
    description: "The 'black box flight recorder' of the system.",
    whatItDoes: "The 'black box flight recorder.'",
    connectedTo: "Records every action from L4, L5, L6, and L3 modules.",
    howItWorks: "Every time ARMS makes a decision (even choosing not to trade), it writes an un-erasable log explaining exactly what math and logic it used. This makes audits instantaneous and perfectly transparent.",
    category: "Reporting",
  },
  L7_Daily: {
    id: "L7_Daily",
    title: "Daily Monitor UI",
    description: "The 'morning dashboard' for the Portfolio Manager.",
    whatItDoes: "The 'morning dashboard.'",
    connectedTo: "Reads from the Session Log.",
    howItWorks: "A visual, easy-to-read screen for the Portfolio Manager to check every morning. It shows the current market weather, active hedges, and what trades are waiting in the queue.",
    category: "Reporting",
  },
  L7_PID: {
    id: "L7_PID",
    title: "PID: Proactive Intelligence Digest",
    description: "The 'investor relations ghostwriter' using AI.",
    whatItDoes: "The 'investor relations ghostwriter.'",
    connectedTo: "Uses the Session Log and the AI Gateway.",
    howItWorks: "Once a month, it looks at every trade ARMS made, uses AI to translate the complex math into a beautifully written, plain-English summary letter, and drafts it for you to send to your Limited Partners (investors). It explains why the system made its moves.",
    category: "Reporting",
  },
  L7_Analytics: {
    id: "L7_Analytics",
    title: "Monthly Analytics & Learning",
    description: "The 'report card' that evaluates system performance.",
    whatItDoes: "The 'report card.'",
    connectedTo: "Reads the Session Log to grade performance.",
    howItWorks: "Evaluates how well the system's decisions worked over the last 30 days. It helps the team (and the CCM learning module) find out what's working perfectly and what needs tweaking.",
    category: "Reporting",
  },
  UI_Dashboard: {
    id: "UI_Dashboard",
    title: "Main Dashboard",
    description: "The 'windshield' of the system.",
    whatItDoes: "The 'windshield.'",
    connectedTo: "Reads live data from the Macro Compass (L2) and the Daily Monitor Engine (L7).",
    howItWorks: "When you open your laptop, this screen shows you the current 'market weather' (Risk-On / Risk-Off), the health of your automated crash insurance (PTRH), and a simple summary of what the system is thinking about doing today.",
    category: "Desktop UI",
  },
  UI_ActionCenter: {
    id: "UI_ActionCenter",
    title: "Action Center",
    description: "The 'approval desk' for major strategic moves.",
    whatItDoes: "The 'approval desk.'",
    connectedTo: "Receives trades from the Confirmation Queue (L6) and sends your clicks to the Broker.",
    howItWorks: "You don't have to write code to trade. When the system wants to make a major strategic move, it pops up here. You see exactly why the system wants to do it, and you simply click 'Approve' or 'Veto.' It also shows countdown timers for automated trades you might want to cancel.",
    category: "Desktop UI",
  },
  UI_ReportsTab: {
    id: "UI_ReportsTab",
    title: "Reports & Logs Tab",
    description: "The 'filing cabinet' for history and investor relations.",
    whatItDoes: "The 'filing cabinet.'",
    connectedTo: "The Session Log and the Proactive Intelligence Digest (PID).",
    howItWorks: "If an investor calls and asks, 'Why did we buy Apple last week?', you click here. It instantly shows you the exact AI logic and math the system used for that trade. It also holds the pre-written monthly investor letters (PID) ready for you to copy, paste, and send.",
    category: "Desktop UI",
  },
  Human_PM: {
    id: "Human_PM",
    title: "Human PM / GP",
    description: "The 'Pilot' of the entire system.",
    whatItDoes: "The 'Pilot.'",
    connectedTo: "The Desktop UI.",
    howItWorks: "You monitor the dashboard, approve the major moves in the Action Center, and handle the human relationships, while the system handles the exhausting day-to-day math, tracking, and execution.",
    category: "Human Oversight",
  },
  Exchange: {
    id: "Exchange",
    title: "Market Brokers / Exchanges",
    description: "External venues where trades are executed.",
    category: "External",
  },
};
