export interface NodeInfo {
  id: string;
  title: string;
  description: string;
  whatItDoes?: string;
  connectedTo?: string;
  howItWorks?: string;
  category: string;
}

export const nodeData: Record<string, NodeInfo> = {
  AWS_ECS: {
    id: "AWS_ECS",
    title: "AWS Fargate/ECS",
    description: "Serverless compute engine for containers. Handles the core execution of trading algorithms and data processing tasks.",
    category: "Infrastructure",
  },
  AWS_RDS: {
    id: "AWS_RDS",
    title: "AWS RDS Postgres",
    description: "Relational database for storing structured data, including trade history and user profiles.",
    category: "Infrastructure",
  },
  AWS_Redis: {
    id: "AWS_Redis",
    title: "Redis ElastiCache",
    description: "In-memory data store for real-time state management and high-speed messaging.",
    category: "Infrastructure",
  },
  DF_Price: {
    id: "DF_Price",
    title: "Market Prices & Equities",
    description: "Real-time and historical price feeds for stocks and ETFs.",
    category: "Data Feeds",
  },
  DF_Macro: {
    id: "DF_Macro",
    title: "FRED Macro Economic Data",
    description: "Integration with Federal Reserve Economic Data (FRED) for macro indicators.",
    category: "Data Feeds",
  },
  DF_PMI: {
    id: "DF_PMI",
    title: "S&P Global PMI",
    description: "Purchasing Managers' Index data providing insights into sector health.",
    category: "Data Feeds",
  },
  DF_Crypto: {
    id: "DF_Crypto",
    title: "Crypto Microstructure",
    description: "Granular data on cryptocurrency order books and on-chain metrics.",
    category: "Data Feeds",
  },
  DF_VIX: {
    id: "DF_VIX",
    title: "VIX & Options Flow",
    description: "Volatility index data and real-time options market activity.",
    category: "Data Feeds",
  },
  L1_Pipeline: {
    id: "L1_Pipeline",
    title: "L1 Ingestion Pipeline",
    description: "The central aggregator that normalizes and cleans incoming data.",
    category: "Data Feeds",
  },

  L2_Score: {
    id: "L2_Score",
    title: "Macro Regime Scoring",
    description: "Analyzes macro data to determine the current market 'regime'.",
    category: "Macro Compass",
  },
  L2_RPE: {
    id: "L2_RPE",
    title: "Regime Probability Engine",
    description: "Uses statistical models to forecast market regime transitions.",
    category: "Macro Compass",
  },
  L2_RSS: {
    id: "L2_RSS",
    title: "Retail Sentiment Score",
    description: "Monitors social sentiment to identify crowded trades.",
    category: "Macro Compass",
  },
  AI_Gateway: {
    id: "AI_Gateway",
    title: "LLM API Gateway",
    description: "Central interface for interacting with large language models (Gemini, Claude, GPT).",
    category: "Intelligence",
  },
  L3_SENTINEL: {
    id: "L3_SENTINEL",
    title: "SENTINEL",
    description: "A 6-gate entry validator that ensures all criteria are met before a trade.",
    category: "Risk & Conviction",
  },
  L3_TDC: {
    id: "L3_TDC",
    title: "Thesis Dependency Checker",
    description: "Continuously audits the original trade thesis against new data using AI.",
    category: "Risk & Conviction",
  },
  L3_CDM: {
    id: "L3_CDM",
    title: "Customer Dependency Map",
    description: "Maps supply chain relationships and alerts to event ripples.",
    category: "Risk & Conviction",
  },
  L3_MICS: {
    id: "L3_MICS",
    title: "Model-Implied Conviction Score",
    description: "Calculates the mathematical conviction level for a trade.",
    category: "Risk & Conviction",
  },
  L3_CDF: {
    id: "L3_CDF",
    title: "Conviction Decay Function",
    description: "Automatically reduces position size over time or if action stagnates.",
    category: "Risk & Conviction",
  },
  L3_CCM: {
    id: "L3_CCM",
    title: "Conviction Calibration",
    description: "A feedback loop that learns from past performance to adjust conviction logic.",
    category: "Risk & Conviction",
  },
  L3_TRP: {
    id: "L3_TRP",
    title: "Thesis Retirement Protocol",
    description: "Enforces disciplined exit logic when a thesis is no longer valid.",
    category: "Risk & Conviction",
  },
  L3_PTRH: {
    id: "L3_PTRH",
    title: "Permanent Tail Risk Hedge",
    description: "Automated insurance against extreme market crashes.",
    category: "Risk & Conviction",
  },
  L3_CAM: {
    id: "L3_CAM",
    title: "Coverage Adequacy Model",
    description: "Monitors whether current hedges are sufficient for the portfolio.",
    category: "Risk & Conviction",
  },
  L3_DSHP: {
    id: "L3_DSHP",
    title: "Defensive Sleeve Harvest",
    description: "Strategically sells safe-haven assets to raise cash during stress.",
    category: "Risk & Conviction",
  },
  L3_Safety: {
    id: "L3_Safety",
    title: "Incapacitation Protocol",
    description: "A 'dead-man's switch' that moves the portfolio to a safe state.",
    category: "Risk & Conviction",
  },
  L3_ARES: {
    id: "L3_ARES",
    title: "Re-Entry System",
    description: "Systematic protocol for buying back into high-conviction positions.",
    category: "Risk & Conviction",
  },
  L3_AUP: {
    id: "L3_AUP",
    title: "Asymmetric Upside Protocol",
    description: "Identifies and manages positions with massive potential upside.",
    category: "Risk & Conviction",
  },
  L4_Master: {
    id: "L4_Master",
    title: "Master Engine",
    description: "The core decision engine that combines all rules into a target portfolio.",
    category: "Execution",
  },
  L5_Orders: {
    id: "L5_Orders",
    title: "Order Book",
    description: "Calculates specific trades required to move to the target portfolio.",
    category: "Execution",
  },
  L6_Queue: {
    id: "L6_Queue",
    title: "Confirmation Queue",
    description: "A safety buffer where trades are held for final validation.",
    category: "Execution",
  },
  L6_Broker: {
    id: "L6_Broker",
    title: "Execution API",
    description: "The technical interface that submits orders to brokers.",
    category: "Execution",
  },
  L7_Log: {
    id: "L7_Log",
    title: "Immutable Session Log",
    description: "The 'black box flight recorder' of the system.",
    whatItDoes: "The 'black box flight recorder.'",
    connectedTo: "Records every action from L4, L5, L6, and L3 modules.",
    howItWorks: "Every time ARMS makes a decision (even choosing not to trade), it writes an un-erasable log explaining exactly what math and logic it used. This makes audits instantaneous and perfectly transparent.",
    category: "Reporting",
  },
  L7_Daily: {
    id: "L7_Daily",
    title: "Daily Monitor UI",
    description: "The 'morning dashboard' for the Portfolio Manager.",
    whatItDoes: "The 'morning dashboard.'",
    connectedTo: "Reads from the Session Log.",
    howItWorks: "A visual, easy-to-read screen for the Portfolio Manager to check every morning. It shows the current market weather, active hedges, and what trades are waiting in the queue.",
    category: "Reporting",
  },
  L7_PID: {
    id: "L7_PID",
    title: "PID: Proactive Intelligence Digest",
    description: "The 'investor relations ghostwriter' using AI.",
    whatItDoes: "The 'investor relations ghostwriter.'",
    connectedTo: "Uses the Session Log and the AI Gateway.",
    howItWorks: "Once a month, it looks at every trade ARMS made, uses AI to translate the complex math into a beautifully written, plain-English summary letter, and drafts it for you to send to your Limited Partners (investors). It explains why the system made its moves.",
    category: "Reporting",
  },
  L7_Analytics: {
    id: "L7_Analytics",
    title: "Monthly Analytics & Learning",
    description: "The 'report card' that evaluates system performance.",
    whatItDoes: "The 'report card.'",
    connectedTo: "Reads the Session Log to grade performance.",
    howItWorks: "Evaluates how well the system's decisions worked over the last 30 days. It helps the team (and the CCM learning module) find out what's working perfectly and what needs tweaking.",
    category: "Reporting",
  },
  UI_Dashboard: {
    id: "UI_Dashboard",
    title: "Main Dashboard",
    description: "The 'windshield' of the system.",
    whatItDoes: "The 'windshield.'",
    connectedTo: "Reads live data from the Macro Compass (L2) and the Daily Monitor Engine (L7).",
    howItWorks: "When you open your laptop, this screen shows you the current 'market weather' (Risk-On / Risk-Off), the health of your automated crash insurance (PTRH), and a simple summary of what the system is thinking about doing today.",
    category: "Desktop UI",
  },
  UI_ActionCenter: {
    id: "UI_ActionCenter",
    title: "Action Center",
    description: "The 'approval desk' for major strategic moves.",
    whatItDoes: "The 'approval desk.'",
    connectedTo: "Receives trades from the Confirmation Queue (L6) and sends your clicks to the Broker.",
    howItWorks: "You don't have to write code to trade. When the system wants to make a major strategic move, it pops up here. You see exactly why the system wants to do it, and you simply click 'Approve' or 'Veto.' It also shows countdown timers for automated trades you might want to cancel.",
    category: "Desktop UI",
  },
  UI_ReportsTab: {
    id: "UI_ReportsTab",
    title: "Reports & Logs Tab",
    description: "The 'filing cabinet' for history and investor relations.",
    whatItDoes: "The 'filing cabinet.'",
    connectedTo: "The Session Log and the Proactive Intelligence Digest (PID).",
    howItWorks: "If an investor calls and asks, 'Why did we buy Apple last week?', you click here. It instantly shows you the exact AI logic and math the system used for that trade. It also holds the pre-written monthly investor letters (PID) ready for you to copy, paste, and send.",
    category: "Desktop UI",
  },
  Human_PM: {
    id: "Human_PM",
    title: "Human PM / GP",
    description: "The 'Pilot' of the entire system.",
    whatItDoes: "The 'Pilot.'",
    connectedTo: "The Desktop UI.",
    howItWorks: "You monitor the dashboard, approve the major moves in the Action Center, and handle the human relationships, while the system handles the exhausting day-to-day math, tracking, and execution.",
    category: "Human Oversight",
  },
  Exchange: {
    id: "Exchange",
    title: "Market Brokers / Exchanges",
    description: "External venues where trades are executed.",
    category: "External",
  },

  // --- NEW: Additional Data Feeds ---
  DF_SEC: {
    id: "DF_SEC",
    title: "SEC EDGAR Feed",
    description: "Ingests SEC Form 4 insider trades and institutional filings via EDGAR.",
    whatItDoes: "Monitors insider buying/selling activity in real-time.",
    connectedTo: "L1 Ingestion Pipeline, SENTINEL Gate checks.",
    howItWorks: "Polls SEC EDGAR for new Form 4 filings, extracts insider trade details (officer name, shares, direction), and flags significant insider selling clusters that may signal thesis risk.",
    category: "Data Feeds",
  },
  DF_RSS: {
    id: "DF_RSS",
    title: "News RSS Feed",
    description: "Public RSS news ingestion for macro event detection and sentiment signals.",
    whatItDoes: "Captures breaking news and macro events.",
    connectedTo: "L1 Ingestion Pipeline, Macro Event State.",
    howItWorks: "Subscribes to curated RSS feeds (Reuters, Bloomberg, Fed), deduplicates stories via event_state, classifies events as macro_event_state types, and injects them into the data pipeline.",
    category: "Data Feeds",
  },

  // --- NEW: ARAS Sub-Modules ---
  ARAS_Delev: {
    id: "ARAS_Delev",
    title: "Deleveraging Risk",
    description: "Detects systemic deleveraging pressure across equity and credit markets.",
    whatItDoes: "Monitors for forced selling cascades.",
    connectedTo: "ARAS Regime Assessor, Macro Compass.",
    howItWorks: "Tracks credit spreads, margin debt levels, and institutional flow data to detect when leveraged players are being forced to unwind. Produces a deleveraging_score (0-1) that feeds into ARAS regime ceiling.",
    category: "ARAS Sub-Modules",
  },
  ARAS_Margin: {
    id: "ARAS_Margin",
    title: "Margin Stress",
    description: "Composite margin pressure indicator combining HY spreads and VIX.",
    whatItDoes: "Measures market-wide margin stress.",
    connectedTo: "ARAS Regime Assessor, VIX & Options data.",
    howItWorks: "Blends high-yield credit spreads with VIX levels into a normalized margin_stress_score. When score exceeds threshold, ARAS lowers the equity allocation ceiling to protect against margin-call cascades.",
    category: "ARAS Sub-Modules",
  },
  ARAS_Gamma: {
    id: "ARAS_Gamma",
    title: "Dealer Gamma",
    description: "Analyzes options dealer gamma positioning to detect volatility inflection points.",
    whatItDoes: "Reads the options market microstructure.",
    connectedTo: "ARAS Regime Assessor, VIX & Options data.",
    howItWorks: "Estimates aggregate dealer gamma exposure. Negative gamma environments amplify volatility (dealers sell into drops), while positive gamma suppresses it. Feeds a gamma_regime signal into ARAS.",
    category: "ARAS Sub-Modules",
  },
  ARAS_CryptoMicro: {
    id: "ARAS_CryptoMicro",
    title: "Crypto Microstructure",
    description: "Evaluates cryptocurrency market health via order book depth and funding rates.",
    whatItDoes: "Monitors crypto market plumbing.",
    connectedTo: "ARAS Regime Assessor, Crypto data feed.",
    howItWorks: "Analyzes BTC/ETH order book depth, perpetual funding rates, and exchange flow data. Detects thin liquidity or extreme funding that precedes crypto dislocations. Outputs crypto_health_score for ARAS.",
    category: "ARAS Sub-Modules",
  },
  ARAS_PCR: {
    id: "ARAS_PCR",
    title: "Put/Call Regime",
    description: "Put/call ratio regime assessment for options market sentiment.",
    whatItDoes: "Gauges options market fear/greed.",
    connectedTo: "ARAS Regime Assessor, VIX & Options data.",
    howItWorks: "Tracks rolling put/call ratios across equity indices. Extreme readings (>1.2 = fear, <0.6 = complacency) produce a pcr_regime_signal that adjusts ARAS defensive posture.",
    category: "ARAS Sub-Modules",
  },
  ARAS_Shutdown: {
    id: "ARAS_Shutdown",
    title: "Shutdown Risk",
    description: "Monitors macro event calendar for government shutdown and debt ceiling risks.",
    whatItDoes: "Tracks political/macro event risk.",
    connectedTo: "ARAS Regime Assessor, FRED Macro data.",
    howItWorks: "Maintains a calendar of known risk events (debt ceiling deadlines, government funding expirations, Fed meetings). Produces a shutdown_risk_score that signals ARAS to pre-position defensively before event dates.",
    category: "ARAS Sub-Modules",
  },
  ARAS_Stress: {
    id: "ARAS_Stress",
    title: "Stress Scenarios",
    description: "Historical stress scenario library for regime comparison and drawdown estimation.",
    whatItDoes: "Compares current conditions to past crises.",
    connectedTo: "ARAS Regime Assessor, all data feeds.",
    howItWorks: "Maintains a library of historical stress events (2008 GFC, 2020 COVID, 2022 rate shock). When current market conditions pattern-match a historical crisis, it estimates potential drawdown and adjusts ARAS ceiling accordingly.",
    category: "ARAS Sub-Modules",
  },

  // --- NEW: Intelligence Layer ---
  AI_ELVT: {
    id: "AI_ELVT",
    title: "Earnings Language Velocity",
    description: "Tracks changes in earnings call language sentiment over time using NLP.",
    whatItDoes: "Detects management tone shifts.",
    connectedTo: "LLM API Gateway, SENTINEL Gate 3.",
    howItWorks: "Processes earnings call transcripts through NLP to score language sentiment. Tracks velocity of change between quarters — a sudden negative shift in previously bullish language is an early warning signal fed into SENTINEL Gate 3.",
    category: "Intelligence",
  },
  AI_JPVI: {
    id: "AI_JPVI",
    title: "Job Posting Velocity Index",
    description: "Monitors hiring trends via job posting data as a leading economic indicator.",
    whatItDoes: "Reads the labor market tea leaves.",
    connectedTo: "LLM API Gateway, Macro Compass.",
    howItWorks: "Scrapes job posting platforms (Adzuna API) to track hiring velocity by sector and geography. A sudden drop in tech job postings, for example, often precedes earnings misses by 1-2 quarters.",
    category: "Intelligence",
  },
  AI_PFVT: {
    id: "AI_PFVT",
    title: "Patent Filing Velocity",
    description: "Tracks patent filing trends as a proxy for R&D investment and innovation cycles.",
    whatItDoes: "Measures innovation momentum.",
    connectedTo: "LLM API Gateway, SENTINEL Gate 3.",
    howItWorks: "Monitors USPTO patent filings by company and sector. Accelerating patent activity signals R&D confidence and future revenue potential. Decelerating filings may indicate strategic retreat.",
    category: "Intelligence",
  },
  AI_SCCR: {
    id: "AI_SCCR",
    title: "Supply Chain Cross-Ref",
    description: "Cross-references supply chain relationships to detect upstream/downstream risk propagation.",
    whatItDoes: "Maps hidden supply chain dependencies.",
    connectedTo: "LLM API Gateway, CDM Supply Chain module.",
    howItWorks: "Maintains a graph of supplier-customer relationships. When a supplier reports trouble (earnings miss, guidance cut), SCCR automatically flags all downstream customers in the portfolio for TDC review.",
    category: "Intelligence",
  },
  AI_Gate3: {
    id: "AI_Gate3",
    title: "Gate 3 Anticipatory",
    description: "Supplementary forward-looking scoring for SENTINEL Gate 3 using AI analysis.",
    whatItDoes: "Looks around corners for thesis risk.",
    connectedTo: "LLM API Gateway, SENTINEL.",
    howItWorks: "Generates an anticipatory score by analyzing upcoming catalysts (earnings dates, FDA decisions, regulatory hearings) and estimating the probability and magnitude of thesis-breaking events before they happen.",
    category: "Intelligence",
  },
  AI_KB: {
    id: "AI_KB",
    title: "Knowledge Base Ingest",
    description: "Vector knowledge base pipeline that indexes system history for AI context retrieval.",
    whatItDoes: "The system's long-term memory.",
    connectedTo: "LLM API Gateway, Session Log, all state files.",
    howItWorks: "Scans session logs, regime history, TDC state, and spec documents. Chunks text (~500 tokens), generates embeddings (OpenAI or hash fallback), stores in vector DB (Pinecone or local JSON). The LLM wrapper queries this to inject relevant historical context into every AI call.",
    category: "Intelligence",
  },

  // --- NEW: Portfolio Guards (L3 Engine Modules) ---
  L3_PDS: {
    id: "L3_PDS",
    title: "Drawdown Sentinel",
    description: "Portfolio-level drawdown monitoring with high-water mark tracking.",
    whatItDoes: "The portfolio's pain threshold.",
    connectedTo: "Master Engine, Session Log.",
    howItWorks: "Tracks the portfolio high-water mark and current drawdown. At -5% triggers alerts, at -8% forces position reduction, at -12% triggers emergency deleveraging. Prevents catastrophic losses through graduated response.",
    category: "Risk & Conviction",
  },
  L3_FEM: {
    id: "L3_FEM",
    title: "Factor Exposure Monitor",
    description: "5-factor portfolio concentration analysis to prevent hidden correlations.",
    whatItDoes: "Detects hidden factor bets.",
    connectedTo: "Master Engine, Kevlar Concentration Limits.",
    howItWorks: "Decomposes portfolio exposure across 5 factors (market, size, value, momentum, quality). Flags when any single factor exceeds 40% of total risk, forcing diversification before the factor reverses.",
    category: "Risk & Conviction",
  },
  L3_Kevlar: {
    id: "L3_Kevlar",
    title: "Kevlar Concentration",
    description: "Hard concentration limits: 22% single-name equity, 3% single crypto position.",
    whatItDoes: "The portfolio's seatbelt.",
    connectedTo: "Master Engine, Order Book.",
    howItWorks: "Enforces non-negotiable position size limits. No single equity position can exceed 22% of NAV. No single crypto position can exceed 3%. These limits are checked before every order and cannot be overridden.",
    category: "Risk & Conviction",
  },
  L3_SLOF: {
    id: "L3_SLOF",
    title: "Leverage Overlay",
    description: "Strategic leverage management tied to regime and conviction levels.",
    whatItDoes: "Controls when leverage is appropriate.",
    connectedTo: "Master Engine, Macro Compass.",
    howItWorks: "In Risk-On regimes with high conviction, allows up to 1.3x leverage for top positions. Automatically deleverages to 1.0x when regime shifts to Risk-Off. Prevents leveraged losses during drawdowns.",
    category: "Risk & Conviction",
  },
  L3_PERM: {
    id: "L3_PERM",
    title: "Premium Extraction",
    description: "Automated covered call writing for income generation on qualifying positions.",
    whatItDoes: "The portfolio's yield enhancer.",
    connectedTo: "Master Engine, Order Book.",
    howItWorks: "Identifies positions suitable for covered call writing (high IV rank, low thesis conviction decay). Writes OTM calls at optimal strike/expiry combinations to generate premium income without significantly capping upside.",
    category: "Risk & Conviction",
  },

  // --- NEW: Execution Pipeline Modules ---
  EX_TOG: {
    id: "EX_TOG",
    title: "Trade Order Generator",
    description: "Converts target portfolio weights into specific trade orders.",
    whatItDoes: "Turns decisions into actions.",
    connectedTo: "Master Engine output, Order Book.",
    howItWorks: "Takes the difference between current portfolio weights and target weights from the Master Engine. Generates OrderRequest objects with ticker, direction (BUY/SELL), quantity, and order type for each required rebalance trade.",
    category: "Execution",
  },
  EX_CB: {
    id: "EX_CB",
    title: "Circuit Breaker",
    description: "Emergency kill switch triggered by extreme market conditions (SPX -5% or VIX >30).",
    whatItDoes: "The system's emergency brake.",
    connectedTo: "Order Book, all execution modules.",
    howItWorks: "Continuously monitors SPX intraday change and VIX level. If SPX drops more than 5% or VIX exceeds 30, ALL pending orders are immediately cancelled and no new orders can be submitted until conditions normalize.",
    category: "Execution",
  },
  EX_PAIE: {
    id: "EX_PAIE",
    title: "Pre-Execution Integrity",
    description: "Final pre-trade validation engine ensuring all safety checks pass before execution.",
    whatItDoes: "The last line of defense before trading.",
    connectedTo: "Order Book, LAEP execution protocol.",
    howItWorks: "Every order passes through PAIE before execution. It verifies: (1) position limits not breached, (2) thesis still valid via TDC, (3) no circuit breaker active, (4) order size within daily limits. Any failure blocks the trade.",
    category: "Execution",
  },
  EX_LAEP: {
    id: "EX_LAEP",
    title: "VIX Execution Protocol",
    description: "5-tier VIX-based execution speed protocol — faster execution in calmer markets.",
    whatItDoes: "Adapts trading speed to volatility.",
    connectedTo: "Pre-Execution Integrity, Confirmation Queue.",
    howItWorks: "Tier 1 (VIX<15): immediate execution. Tier 2 (15-20): 2-hour delay. Tier 3 (20-25): 4-hour delay with size reduction. Tier 4 (25-30): next-day execution. Tier 5 (>30): manual approval required. Prevents rushing into volatile markets.",
    category: "Execution",
  },
  EX_StratQ: {
    id: "EX_StratQ",
    title: "Strategic Queue",
    description: "Regime-triggered deployment queue for strategic capital allocation shifts.",
    whatItDoes: "Queues big moves for the right moment.",
    connectedTo: "Confirmation Queue, Macro Compass.",
    howItWorks: "When macro regime shifts (e.g., Risk-Off → Recovery), the system queues large strategic reallocation orders. These execute only when regime confirmation persists for 3+ consecutive sessions, preventing whipsaws.",
    category: "Execution",
  },
  EX_QueueGov: {
    id: "EX_QueueGov",
    title: "Queue Governance",
    description: "State machine managing queue transitions, signal aggregation, and persistence.",
    whatItDoes: "The queue's traffic controller.",
    connectedTo: "Confirmation Queue, Strategic Queue, Session Log.",
    howItWorks: "Manages queue lifecycle states (PENDING → APPROVED → EXECUTING → COMPLETE). Aggregates signals from risk and conviction modules to determine queue priority. Logs all transitions for audit trail.",
    category: "Execution",
  },
  EX_Corr: {
    id: "EX_Corr",
    title: "Correlation Monitor",
    description: "30-day rolling correlation tracker between equity and crypto portfolios.",
    whatItDoes: "Watches for dangerous convergence.",
    connectedTo: "Kevlar Concentration, Master Engine.",
    howItWorks: "Calculates rolling 30-day correlation between equity and crypto returns. When correlation exceeds 0.7, the portfolio's diversification benefit is eroding — triggers Kevlar to reduce the more volatile leg.",
    category: "Execution",
  },
  EX_Escal: {
    id: "EX_Escal",
    title: "Escalation Engine",
    description: "Cumulative daily loss auto-suppress engine that blocks trades after excessive losses.",
    whatItDoes: "Stops the bleeding automatically.",
    connectedTo: "Confirmation Queue, Session Log.",
    howItWorks: "Tracks cumulative realized losses within each trading session. At -2% daily loss, reduces remaining order sizes by 50%. At -3%, blocks all new BUY orders. At -5%, halts all trading and alerts PM. Prevents tilt-driven losses.",
    category: "Execution",
  },
  EX_Overnight: {
    id: "EX_Overnight",
    title: "Overnight Monitor",
    description: "Pre-market ES/VIX futures gap monitor for overnight risk detection.",
    whatItDoes: "Watches markets while you sleep.",
    connectedTo: "Master Engine (Phase 0), Circuit Breaker.",
    howItWorks: "Checks ES futures and VIX at system startup (before market open). If ES gaps down >2% or VIX spikes >25% overnight, triggers pre-market defensive adjustments before the regular orchestration cycle begins.",
    category: "Execution",
  },
  EX_PMProtocol: {
    id: "EX_PMProtocol",
    title: "PM Co-Sign Protocol",
    description: "GP/PM manual approval requirement for Tier 1 (large) trade orders.",
    whatItDoes: "Human-in-the-loop for big decisions.",
    connectedTo: "Confirmation Queue, Human PM, Action Center UI.",
    howItWorks: "Any order exceeding the Tier 1 threshold (major position changes) requires explicit GP co-sign before execution. The PM receives a notification in the Action Center with full rationale and has 24 hours to approve or veto.",
    category: "Execution",
  },

  // --- NEW: Reporting ---
  L7_EOD: {
    id: "L7_EOD",
    title: "EOD Snapshot",
    description: "End-of-day 5-field closing check capturing portfolio state at market close.",
    whatItDoes: "The daily closing photograph.",
    connectedTo: "Session Log, Daily Monitor.",
    howItWorks: "At 4:01 PM ET, captures: (1) total NAV, (2) daily P&L, (3) active position count, (4) hedge coverage ratio, (5) regime state. This snapshot is the source of truth for overnight risk calculations and next-day reporting.",
    category: "Reporting",
  },
  L7_PerfAttr: {
    id: "L7_PerfAttr",
    title: "Performance Attribution",
    description: "Module-level alpha attribution analysis showing which ARMS modules add value.",
    whatItDoes: "The system's performance review.",
    connectedTo: "Session Log, Monthly Analytics.",
    howItWorks: "Decomposes portfolio returns into contributions from each ARMS module (SENTINEL entry timing, PTRH hedge savings, CDF exit timing, etc.). Identifies which modules are generating alpha and which need recalibration.",
    category: "Reporting",
  },
  L7_RegimeHist: {
    id: "L7_RegimeHist",
    title: "Regime History",
    description: "Complete regime transition history with timestamps and confidence scores.",
    whatItDoes: "The market weather diary.",
    connectedTo: "Macro Compass, Session Log.",
    howItWorks: "Records every regime transition (Risk-On → Cautious → Risk-Off → Recovery) with exact timestamp, confidence score, and triggering indicators. Used by CCM for learning and by the Monthly Analytics for pattern analysis.",
    category: "Reporting",
  },

  // --- NEW: Scheduling ---
  SCHED_Master: {
    id: "SCHED_Master",
    title: "Master Scheduler",
    description: "APScheduler-based job orchestration for all timed ARMS operations.",
    whatItDoes: "The system's internal clock.",
    connectedTo: "Main orchestration loop, KB Ingest, EOD Snapshot.",
    howItWorks: "Manages all scheduled jobs: daily orchestration cycle (6:30 AM ET), EOD snapshot (4:01 PM), weekly systematic scan (Sunday), monthly analytics generation, and continuous KB ingest. Runs on AWS Fargate with health monitoring.",
    category: "Scheduling",
  },
};
