"""
ARMS Module: Permanent Tail Risk Hedge (PTRH) Full Automation

This module provides the full, Tier-0 autonomous operation for the PTRH. It
uses the regime-dependent sizing table from THB v4.0 FINAL to determine required
coverage and executes all necessary actions (rolls, resizing, drift correction)
without human intervention.

"Silence is trust in the architecture."

Reference: ARMS THB v4.0 FINAL — Section 6 (PTRH)
"""

import datetime
from dataclasses import dataclass, field
from typing import List, Literal, Optional, Tuple, Dict
# --- Internal Imports ---
from execution.order_request import OrderRequest
from execution.interfaces import Broker
from reporting.audit_log import SessionLogEntry, append_to_log

# --- PTRH Regime Sizing Table (THB v4.0 FINAL, Section 6.2) ---
# Base coverage: 1.2% NAV
# Strike: 10-15% OTM QQQ puts (target ~12.5%)
PTRH_BASE_COVERAGE_PCT = 0.012

# Regime multipliers (THB v4.0 FINAL — supersedes all prior drafts)
# CRASH: 1.50x HOLD — no new buys (implied vol too expensive)
PTRH_REGIME_TABLE = {
    "RISK_ON":    {"multiplier": 1.00, "coverage_pct": 0.012, "strc_reserve": 0.0},
    "WATCH":      {"multiplier": 1.25, "coverage_pct": 0.015, "strc_reserve": 0.0},
    "NEUTRAL":    {"multiplier": 1.25, "coverage_pct": 0.015, "strc_reserve": 0.50},
    "DEFENSIVE":  {"multiplier": 1.50, "coverage_pct": 0.018, "strc_reserve": 1.00},
    "CRASH":      {"multiplier": 1.50, "coverage_pct": 0.018, "strc_reserve": 1.00},
}


@dataclass
class PTRHInputs:
    """
    Inputs required for PTRH sizing (replaces CAM).
    Uses simple regime table lookup per THB v4.0 FINAL.
    """
    nav: float
    regime_label: str  # RISK_ON, WATCH, NEUTRAL, DEFENSIVE, CRASH
    regime_score: float


def calculate_ptrh_required_notional(inputs: PTRHInputs) -> float:
    """
    Calculate required PTRH put notional using regime table.
    THB v4.0 FINAL: CAM removed from scope. Simple regime multiplier only.
    """
    entry = PTRH_REGIME_TABLE.get(inputs.regime_label, PTRH_REGIME_TABLE["RISK_ON"])
    coverage_pct = entry["coverage_pct"]
    return coverage_pct * inputs.nav

# --- Data Structures ---

@dataclass
class OptionsPosition:
    """
    Represents a single options position in the portfolio.
    Used for tracking existing PTRH hedges.
    """
    ticker: str
    option_type: Literal['PUT', 'CALL']
    strike: float
    expiry: str  # ISO date format 'YYYY-MM-DD'
    contracts: int
    notional_value: float
    
    # Optional fields generated by Addendum 6 strike selection
    con_id: Optional[int] = None
    delta: Optional[float] = None
    bid: Optional[float] = None
    ask: Optional[float] = None

    @property
    def dte(self) -> int:
        """Calculates the Days To Expiration (DTE)."""
        expiry_date = datetime.datetime.strptime(self.expiry, '%Y-%m-%d').date()
        return (expiry_date - datetime.date.today()).days

@dataclass
class PTRHStatus:
    """
    Represents the complete status of the PTRH module for monitoring.
    Based on ARMS Module Specification — Section 1.5.
    """
    regime: str                 # current canonical regime label
    multiplier: float           # current sizing multiplier from CAM/Regime
    target_notional_pct: float  # % of NAV in puts
    actual_notional_pct: float  # actual current coverage
    coverage_drift_pct: float   # abs(target - actual)
    nearest_expiry_dte: int     # days to expiration of nearest position
    last_roll_date: str         # ISO date of most recent roll
    dual_risk_active: bool      # PM-declared dual-risk flag
    dual_risk_standard_pct: float # override notional if dual_risk_active
    last_action: str            # 'NONE'|'ROLL'|'RESIZE'|'CORRECT_DRIFT'
    last_action_timestamp: str  # ISO format
    alerts: List[str] = field(default_factory=list)
    generated_orders: List[OrderRequest] = field(default_factory=list)

# --- Core Execution Support ---

def _submit_ptrh_order(action: Literal['BUY_PUT', 'SELL_PUT'], 
                       quantity: float,
                       quantity_kind: Literal['CONTRACTS', 'NOTIONAL_USD'],
                       signal: str, 
                       tier: int = 0,
                       contract: Optional[OptionsPosition] = None):
    """
    Standardized internal helper to submit PTRH orders via the broker API logic.
    In a real system, this would call broker_api.submit_order().
    """
    # Create the OrderRequest as defined in L5/L6 of FSD v1.1
    order = OrderRequest(
        ticker=contract.ticker if contract else "QQQ",
        action=action,
        quantity=quantity,
        quantity_kind=quantity_kind,
        con_id=contract.con_id if contract else None,
        strike=contract.strike if contract else None,
        expiry=contract.expiry if contract else None,
        option_right='P' if contract and contract.option_type == 'PUT' else None,
        order_type="LIMIT" if tier == 0 else "MARKET",
        limit_price=contract.ask if contract and contract.ask else None,
        execution_window_min=30,
        slippage_budget_bps=8.0,
        priority=1,
        triggering_module="PTRH",
        triggering_signal=signal,
        tier=tier,
        confirmation_required=(tier == 1),
        veto_window_hours=0.0
    )
    
    # Optional logic to pass the con_id to broker
    if contract and contract.con_id:
        object.__setattr__(order, 'con_id', contract.con_id)

    # Log the action immediately to the immutable audit trail
    append_to_log(SessionLogEntry(
        timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        action_type='TRADE',
        triggering_module='PTRH',
        triggering_signal=signal,
        correlation_id=order.correlation_id,
        ticker=order.ticker,
        regime_at_action="N/A" # Would be passed in a real system
    ))
    
    # Placeholder: print to console for development visibility
    print(f"[PTRH] {action} planned for {order.ticker}: {signal} ({quantity} {quantity_kind})")
    return order

def _resolve_delta_primary_strike(broker: Broker, ticker: str, target_delta: float = -0.35) -> Optional[OptionsPosition]:
    """
    Addendum 6: Delta-Primary Strike Selection Algorithm with 4-Gate Fallback Hierarchy
    """
    if not hasattr(broker, 'get_options_chain') or not hasattr(broker, 'get_market_data'):
        return None
        
    print(f"[PTRH] Resolving Delta-Primary Strike for {ticker} (Target Delta: {target_delta})")
    
    try:
        raw_chain = broker.get_options_chain(ticker)
        if not raw_chain:
            print("[PTRH] Chain pull failed.")
            return None
            
        today = datetime.date.today()
        
        # Pull live spot price to narrow options chain
        import ib_insync as ibi
        underlying = getattr(broker, 'ib', None).qualifyContracts(ibi.Stock(ticker, 'SMART', 'USD'))[0] if getattr(broker, 'ib', None) else None
        if not underlying:
            return None
        spot_ticker = broker.get_market_data([underlying])[0]
        spot_price = spot_ticker.marketPrice()

        # Gate Hierarchy Definitions (Addendum 6, Section 3)
        gates = [
            {"level": 1, "name": "STANDARD", "delta": (-0.40, -0.30), "dte": (60, 90), "spread_pct": 0.05},
            {"level": 2, "name": "RELAXED", "delta": (-0.42, -0.28), "dte": (55, 95), "spread_pct": 0.07},
            {"level": 3, "name": "EXTENDED", "delta": (-0.45, -0.25), "dte": (45, 105), "spread_pct": 0.10}
        ]

        best_contract = None
        active_gate = None
        min_delta_diff = float('inf')

        # Fallback Hierarchy Loop
        for gate in gates:
            print(f"[PTRH] Evaluating Gate {gate['level']} ({gate['name']}) constraints...")
            valid_expiries = []
            for c in raw_chain:
                expiry_date = datetime.datetime.strptime(c.lastTradeDateOrContractMonth, '%Y%m%d').date()
                dte = (expiry_date - today).days
                if gate['dte'][0] <= dte <= gate['dte'][1]:
                    valid_expiries.append(c)
                    
            if not valid_expiries:
                continue

        # Narrow to strikes in 10-15% OTM range per THB v4.0 FINAL
            narrowed = [c for c in valid_expiries if spot_price * 0.85 <= float(c.strike) <= spot_price * 0.90]
            tickers = broker.get_market_data(narrowed, require_greeks=True)
            
            for t in tickers:
                if not t.modelGreeks or not t.modelGreeks.delta:
                    continue
                    
                delta = t.modelGreeks.delta
                spread = t.ask - t.bid if t.ask and t.bid else float('inf')
                mid = (t.bid + t.ask) / 2 if t.ask and t.bid else 1.0
                spread_pct = spread / mid if mid > 0 else float('inf')
                
                # Gate Logic Validation
                if gate['delta'][0] <= delta <= gate['delta'][1] and spread_pct <= gate['spread_pct']:
                    diff = abs(delta - target_delta)
                    if diff < min_delta_diff:
                        min_delta_diff = diff
                        best_contract = t
            
            if best_contract:
                active_gate = gate
                break # Exit the fallback loop, a compliant contract was found!

        # Gate 4: Abort (No contract satisfies Gate 3)
        if not best_contract or not active_gate:
            print("[PTRH] Gate 4 Abort: No contracts met Gate 3 (EXTENDED) constraints. True market dislocation detected.")
            append_to_log(SessionLogEntry(
                timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
                action_type='PTRH_NO_EXECUTE',
                triggering_module='PTRH',
                triggering_signal="Gate 4 Abort: No compliant options available. PTRH budget preserved in cash sleeve.",
                ticker=ticker
            ))
            return None
            
        # Compile result
        c = best_contract.contract
        dte = (datetime.datetime.strptime(c.lastTradeDateOrContractMonth, '%Y%m%d').date() - today).days
        otm_pct = (spot_price - c.strike) / spot_price if spot_price else 0.0
        
        log_message = f"Spot QQQ | Delta {best_contract.modelGreeks.delta:.3f} | OTM% {otm_pct:.2%} | DTE {dte} | Guardrail: Gate {active_gate['level']} ({active_gate['name']})"
        print(f"[PTRH] Calibration Log: {log_message}")
        
        # Addendum 6 Logging & Notifications based on Fallback Level
        if active_gate['level'] == 2:
            append_to_log(SessionLogEntry(
                timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
                action_type='PTRH_FALLBACK_2',
                triggering_module='PTRH',
                triggering_signal=f"Gate 2 (RELAXED) invoked. Queue ARMS Architecture Review.",
                ticker=ticker
            ))
        elif active_gate['level'] == 3:
            append_to_log(SessionLogEntry(
                timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
                action_type='PTRH_FALLBACK_3',
                triggering_module='PTRH',
                triggering_signal=f"PTRH-SPEC-DRIFT Alert: Gate 3 (EXTENDED) invoked. Market snapshot generated. Immediate PM notification required.",
                ticker=ticker
            ))
            
        return OptionsPosition(
            ticker=c.symbol,
            option_type='PUT',
            strike=c.strike,
            expiry=datetime.datetime.strptime(c.lastTradeDateOrContractMonth, '%Y%m%d').strftime('%Y-%m-%d'),
            contracts=1, # Default placeholder, sized later
            notional_value=0.0,
            con_id=c.conId,
            delta=best_contract.modelGreeks.delta,
            bid=best_contract.bid,
            ask=best_contract.ask
        )
        
    except Exception as e:
        print(f"[PTRH] Error resolving strike: {e}")
        return None

def _estimate_contracts_for_notional(target_notional: float, contract: Optional[OptionsPosition]) -> int:
    if contract is None:
        return 0
    option_premium = contract.ask or contract.bid
    if option_premium is None or option_premium <= 0:
        return 0
    contract_multiplier = 100.0
    per_contract_cost = float(option_premium) * contract_multiplier
    if per_contract_cost <= 0:
        return 0
    return max(1, int(round(float(target_notional) / per_contract_cost)))

# --- Main Logic Module ---

def run_ptrh_module(ptrh_inputs: PTRHInputs, 
                    current_positions: List[OptionsPosition],
                    broker: Optional[Broker] = None,
                    dual_risk_override_pct: Optional[float] = None) -> PTRHStatus:
    """
    Runs the full Tier-0 PTRH management logic using the Addendum 6 Delta-Primary architecture.
    THB v4.0 FINAL: Uses regime table sizing (CAM removed from scope).
    """
    alerts = []
    generated_orders = []
    last_action = "NONE"
    
    # 1. Determine target notional using regime table (replaces CAM)
    required_notional = calculate_ptrh_required_notional(ptrh_inputs)
    if dual_risk_override_pct is not None:
        required_notional = ptrh_inputs.nav * dual_risk_override_pct

    # CRASH regime: hold existing, no new buys
    regime_entry = PTRH_REGIME_TABLE.get(ptrh_inputs.regime_label, PTRH_REGIME_TABLE["RISK_ON"])
    is_crash = ptrh_inputs.regime_label == "CRASH"
    
    actual_notional = sum(p.notional_value for p in current_positions)
    target_pct = required_notional / ptrh_inputs.nav if ptrh_inputs.nav > 0 else 0
    actual_pct = actual_notional / ptrh_inputs.nav if ptrh_inputs.nav > 0 else 0
    drift = (actual_pct / target_pct) - 1 if target_pct > 0 else 0
    
    # 2. Addendum 6 Delta-Primary Strike Selection Simulation
    # Under the new protocol, ARMS must search the chain for a -0.35 delta QQQ put.
    print("[PTRH] Scanning QQQ options chain for -0.35 Delta target (Addendum 6 Protocol)...")
    
    target_contract = None
    if broker and broker.is_connected:
        target_contract = _resolve_delta_primary_strike(broker, "QQQ", -0.35)
    
    if not target_contract:
        alerts.append("PTRH target contract resolution failed; no compliant live contract returned.")
        append_to_log(SessionLogEntry(
            timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
            action_type='PTRH_TARGET_UNRESOLVED',
            triggering_module='PTRH',
            triggering_signal='No compliant live target contract returned from options scan.',
            ticker='QQQ'
        ))
        
    selected_contract_delta = target_contract.delta if target_contract and target_contract.delta is not None else None
    selected_contract_dte = target_contract.dte if target_contract else None
    selected_contract_otm_pct = None
    
    # 3. Check DTE for rolls (Priority 1)
    roll_occurred = False
    for pos in current_positions:
        if pos.dte <= 30:
            signal = f"DTE Roll: {pos.expiry} is at {pos.dte} days. Delta-Optimal Strike Selection (-0.35 tgt) via Gate 1."
            if target_contract is None:
                alerts.append(f"PTRH roll due for {pos.expiry}, but no live replacement contract was resolved.")
                continue
            sell_contracts = max(1, int(abs(pos.contracts)))
            buy_contracts = _estimate_contracts_for_notional(pos.notional_value, target_contract)
            if buy_contracts <= 0:
                alerts.append("PTRH roll contract sizing failed; no executable contract count derived.")
                continue
            generated_orders.append(_submit_ptrh_order('SELL_PUT', sell_contracts, 'CONTRACTS', signal, contract=pos))
            generated_orders.append(_submit_ptrh_order('BUY_PUT', buy_contracts, 'CONTRACTS', signal, contract=target_contract))
            last_action = "ROLL"
            roll_occurred = True
    
    # 4. Check notional drift and auto-correct (Priority 2)
    if not roll_occurred: 
        is_under_hedged = drift < -0.05
        is_over_hedged = drift > 0.15
        
        if is_under_hedged or is_over_hedged:
            delta_notional = required_notional - actual_notional
            action = 'BUY_PUT' if delta_notional > 0 else 'SELL_PUT'

            # THB v4.0 FINAL: CRASH regime = hold existing, no new buys
            if is_crash and action == 'BUY_PUT':
                alerts.append("CRASH regime: implied vol too expensive for new puts. Holding existing coverage.")
            else:
                signal = f"Drift Correction: actual {actual_pct:.2%} vs target {target_pct:.2%}. Delta-Optimal Strike Selected. Delta: ${abs(delta_notional):,.2f}"
                active_contract = target_contract if action == 'BUY_PUT' else (current_positions[0] if current_positions else target_contract)

                if active_contract is None:
                    alerts.append("PTRH drift correction required, but no live contract was available for execution.")
                else:
                    if action == 'BUY_PUT':
                        contract_qty = _estimate_contracts_for_notional(abs(delta_notional), active_contract)
                    else:
                        contract_qty = max(1, int(abs(active_contract.contracts)))

                    if contract_qty <= 0:
                        alerts.append("PTRH drift correction sizing failed; no executable contract count derived.")
                    else:
                        generated_orders.append(_submit_ptrh_order(action, contract_qty, 'CONTRACTS', signal, contract=active_contract))
                        last_action = "CORRECT_DRIFT"
    
    # 5. Prepare Status for Monitoring
    nearest_dte = min([p.dte for p in current_positions]) if current_positions else 0

    status = PTRHStatus(
        regime=ptrh_inputs.regime_label, 
        multiplier=regime_entry["multiplier"],
        target_notional_pct=target_pct,
        actual_notional_pct=actual_pct,
        coverage_drift_pct=drift * 100,
        nearest_expiry_dte=nearest_dte,
        last_roll_date=datetime.date.today().isoformat() if last_action == "ROLL" else "N/A",
        dual_risk_active=(dual_risk_override_pct is not None),
        dual_risk_standard_pct=dual_risk_override_pct if dual_risk_override_pct else 0.0,
        last_action=last_action,
        last_action_timestamp=datetime.datetime.now().isoformat() if last_action != "NONE" else "",
        alerts=alerts,
        generated_orders=generated_orders
    )
    
    # Addendum 6 Drift Logging
    # print(f"[PTRH] Calibration Log: Spot QQQ | Delta {selected_contract_delta} | OTM% {selected_contract_otm_pct:.2%} | DTE {selected_contract_dte} | Guardrail: Gate 1 (Standard)")
    
    return status

if __name__ == '__main__':
    print("ARMS PTRH Module Active (Simulation Mode)")
    
    # Simulate a RISK_ON scenario
    test_inputs = PTRHInputs(
        nav=50_000_000,
        regime_label="RISK_ON",
        regime_score=0.25,
    )
    
    # Existing put at 35 DTE, correct sizing
    test_pos = [OptionsPosition("QQQ", "PUT", 400, "2026-05-05", 100, 600_000)]
    
    res = run_ptrh_module(test_inputs, test_pos)
    print(f"Status: {res}")
