"""
ARMS Module: Permanent Tail Risk Hedge (PTRH) Full Automation

This module provides the full, Tier-0 autonomous operation for the PTRH. It
integrates with the Coverage Adequacy Model (CAM) to determine required coverage
and executes all necessary actions (rolls, resizing, drift correction) without
human intervention.

"Silence is trust in the architecture."

Reference: ARMS Module Specification — PTRH Automation + DSHP, Section 1
Reference: ARMS Addendum 4 — Governing Principle + PTRH Coverage Adequacy Model
"""

import datetime
from dataclasses import dataclass, field
from typing import List, Literal, Optional, Tuple, Dict
# --- Internal Imports ---
from engine.cam import calculate_required_notional, CamInputs
from execution.order_request import OrderRequest
from execution.interfaces import Broker
from reporting.audit_log import SessionLogEntry, append_to_log

# --- Data Structures ---

@dataclass
class OptionsPosition:
    """
    Represents a single options position in the portfolio.
    Used for tracking existing PTRH hedges.
    """
    ticker: str
    option_type: Literal['PUT', 'CALL']
    strike: float
    expiry: str  # ISO date format 'YYYY-MM-DD'
    contracts: int
    notional_value: float
    
    # Optional fields generated by Addendum 6 strike selection
    con_id: Optional[int] = None
    delta: Optional[float] = None
    bid: Optional[float] = None
    ask: Optional[float] = None

    @property
    def dte(self) -> int:
        """Calculates the Days To Expiration (DTE)."""
        expiry_date = datetime.datetime.strptime(self.expiry, '%Y-%m-%d').date()
        return (expiry_date - datetime.date.today()).days

@dataclass
class PTRHStatus:
    """
    Represents the complete status of the PTRH module for monitoring.
    Based on ARMS Module Specification — Section 1.5.
    """
    regime: str                 # current canonical regime label
    multiplier: float           # current sizing multiplier from CAM/Regime
    target_notional_pct: float  # % of NAV in puts
    actual_notional_pct: float  # actual current coverage
    coverage_drift_pct: float   # abs(target - actual)
    nearest_expiry_dte: int     # days to expiration of nearest position
    last_roll_date: str         # ISO date of most recent roll
    dual_risk_active: bool      # PM-declared dual-risk flag
    dual_risk_standard_pct: float # override notional if dual_risk_active
    last_action: str            # 'NONE'|'ROLL'|'RESIZE'|'CORRECT_DRIFT'
    last_action_timestamp: str  # ISO format
    alerts: List[str] = field(default_factory=list)
    generated_orders: List[OrderRequest] = field(default_factory=list)

# --- Core Execution Support ---

def _submit_ptrh_order(action: Literal['BUY_PUT', 'SELL_PUT'], 
                       notional: float, 
                       signal: str, 
                       tier: int = 0,
                       contract: Optional[OptionsPosition] = None):
    """
    Standardized internal helper to submit PTRH orders via the broker API logic.
    In a real system, this would call broker_api.submit_order().
    """
    # Create the OrderRequest as defined in L5/L6 of FSD v1.1
    order = OrderRequest(
        ticker=contract.ticker if contract else "QQQ",
        action=action,
        quantity=notional, # Transitional semantics: hedge notional placeholder
        order_type="LIMIT" if tier == 0 else "MARKET",
        limit_price=contract.ask if contract and contract.ask else None,
        execution_window_min=30,
        slippage_budget_bps=8.0,
        priority=1,
        triggering_module="PTRH",
        triggering_signal=signal,
        tier=tier,
        confirmation_required=(tier == 1),
        veto_window_hours=0.0
    )
    
    # Optional logic to pass the con_id to broker
    if contract and contract.con_id:
        object.__setattr__(order, 'con_id', contract.con_id)

    # Log the action immediately to the immutable audit trail
    append_to_log(SessionLogEntry(
        timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        action_type='TRADE',
        triggering_module='PTRH',
        triggering_signal=signal,
        correlation_id=order.correlation_id,
        ticker=order.ticker,
        regime_at_action="N/A" # Would be passed in a real system
    ))
    
    # Placeholder: print to console for development visibility
    print(f"[PTRH] {action} planned for {order.ticker}: {signal} (${notional:,.2f} notional)")
    return order

def _resolve_delta_primary_strike(broker: Broker, ticker: str, target_delta: float = -0.35) -> Optional[OptionsPosition]:
    """
    Addendum 6: Delta-Primary Strike Selection Algorithm with 4-Gate Fallback Hierarchy
    """
    if not hasattr(broker, 'get_options_chain') or not hasattr(broker, 'get_market_data'):
        return None
        
    print(f"[PTRH] Resolving Delta-Primary Strike for {ticker} (Target Delta: {target_delta})")
    
    try:
        raw_chain = broker.get_options_chain(ticker)
        if not raw_chain:
            print("[PTRH] Chain pull failed.")
            return None
            
        today = datetime.date.today()
        
        # Pull live spot price to narrow options chain
        underlying = getattr(broker, 'ib', None).qualifyContracts(getattr(broker, 'ib').Stock(ticker, 'SMART', 'USD'))[0] if getattr(broker, 'ib', None) else None
        if not underlying:
            return None
        spot_ticker = broker.get_market_data([underlying])[0]
        spot_price = spot_ticker.marketPrice()

        # Gate Hierarchy Definitions (Addendum 6, Section 3)
        gates = [
            {"level": 1, "name": "STANDARD", "delta": (-0.40, -0.30), "dte": (60, 90), "spread_pct": 0.05},
            {"level": 2, "name": "RELAXED", "delta": (-0.42, -0.28), "dte": (55, 95), "spread_pct": 0.07},
            {"level": 3, "name": "EXTENDED", "delta": (-0.45, -0.25), "dte": (45, 105), "spread_pct": 0.10}
        ]

        best_contract = None
        active_gate = None
        min_delta_diff = float('inf')

        # Fallback Hierarchy Loop
        for gate in gates:
            print(f"[PTRH] Evaluating Gate {gate['level']} ({gate['name']}) constraints...")
            valid_expiries = []
            for c in raw_chain:
                expiry_date = datetime.datetime.strptime(c.lastTradeDateOrContractMonth, '%Y%m%d').date()
                dte = (expiry_date - today).days
                if gate['dte'][0] <= dte <= gate['dte'][1]:
                    valid_expiries.append(c)
                    
            if not valid_expiries:
                continue

            # Narrow to strikes roughly near ATM to deep OTM
            narrowed = [c for c in valid_expiries if spot_price * 0.80 <= float(c.strike) <= spot_price * 1.05]
            tickers = broker.get_market_data(narrowed)
            
            for t in tickers:
                if not t.modelGreeks or not t.modelGreeks.delta:
                    continue
                    
                delta = t.modelGreeks.delta
                spread = t.ask - t.bid if t.ask and t.bid else float('inf')
                mid = (t.bid + t.ask) / 2 if t.ask and t.bid else 1.0
                spread_pct = spread / mid if mid > 0 else float('inf')
                
                # Gate Logic Validation
                if gate['delta'][0] <= delta <= gate['delta'][1] and spread_pct <= gate['spread_pct']:
                    diff = abs(delta - target_delta)
                    if diff < min_delta_diff:
                        min_delta_diff = diff
                        best_contract = t
            
            if best_contract:
                active_gate = gate
                break # Exit the fallback loop, a compliant contract was found!

        # Gate 4: Abort (No contract satisfies Gate 3)
        if not best_contract or not active_gate:
            print("[PTRH] Gate 4 Abort: No contracts met Gate 3 (EXTENDED) constraints. True market dislocation detected.")
            append_to_log(SessionLogEntry(
                timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
                action_type='PTRH_NO_EXECUTE',
                triggering_module='PTRH',
                triggering_signal="Gate 4 Abort: No compliant options available. PTRH budget preserved in cash sleeve.",
                ticker=ticker
            ))
            return None
            
        # Compile result
        c = best_contract.contract
        dte = (datetime.datetime.strptime(c.lastTradeDateOrContractMonth, '%Y%m%d').date() - today).days
        otm_pct = (spot_price - c.strike) / spot_price if spot_price else 0.0
        
        log_message = f"Spot QQQ | Delta {best_contract.modelGreeks.delta:.3f} | OTM% {otm_pct:.2%} | DTE {dte} | Guardrail: Gate {active_gate['level']} ({active_gate['name']})"
        print(f"[PTRH] Calibration Log: {log_message}")
        
        # Addendum 6 Logging & Notifications based on Fallback Level
        if active_gate['level'] == 2:
            append_to_log(SessionLogEntry(
                timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
                action_type='PTRH_FALLBACK_2',
                triggering_module='PTRH',
                triggering_signal=f"Gate 2 (RELAXED) invoked. Queue ARMS Architecture Review.",
                ticker=ticker
            ))
        elif active_gate['level'] == 3:
            append_to_log(SessionLogEntry(
                timestamp=datetime.datetime.now(datetime.timezone.utc).isoformat(),
                action_type='PTRH_FALLBACK_3',
                triggering_module='PTRH',
                triggering_signal=f"PTRH-SPEC-DRIFT Alert: Gate 3 (EXTENDED) invoked. Market snapshot generated. Immediate PM notification required.",
                ticker=ticker
            ))
            
        return OptionsPosition(
            ticker=c.symbol,
            option_type='PUT',
            strike=c.strike,
            expiry=datetime.datetime.strptime(c.lastTradeDateOrContractMonth, '%Y%m%d').strftime('%Y-%m-%d'),
            contracts=1, # Default placeholder, sized later
            notional_value=0.0,
            con_id=c.conId,
            delta=best_contract.modelGreeks.delta,
            bid=best_contract.bid,
            ask=best_contract.ask
        )
        
    except Exception as e:
        print(f"[PTRH] Error resolving strike: {e}")
        return None

# --- Main Logic Module ---

def run_ptrh_module(cam_inputs: CamInputs, 
                    current_positions: List[OptionsPosition],
                    broker: Optional[Broker] = None,
                    dual_risk_override_pct: Optional[float] = None) -> PTRHStatus:
    """
    Runs the full Tier-0 PTRH management logic using the Addendum 6 Delta-Primary architecture.
    """
    alerts = []
    generated_orders = []
    last_action = "NONE"
    
    # 1. Determine target notional using CAM
    required_notional = calculate_required_notional(cam_inputs)
    if dual_risk_override_pct is not None:
        required_notional = cam_inputs.nav * dual_risk_override_pct
    
    actual_notional = sum(p.notional_value for p in current_positions)
    target_pct = required_notional / cam_inputs.nav if cam_inputs.nav > 0 else 0
    actual_pct = actual_notional / cam_inputs.nav if cam_inputs.nav > 0 else 0
    drift = (actual_pct / target_pct) - 1 if target_pct > 0 else 0
    
    # 2. Addendum 6 Delta-Primary Strike Selection Simulation
    # Under the new protocol, ARMS must search the chain for a -0.35 delta QQQ put.
    print("[PTRH] Scanning QQQ options chain for -0.35 Delta target (Addendum 6 Protocol)...")
    
    target_contract = None
    if broker and broker.is_connected:
        target_contract = _resolve_delta_primary_strike(broker, "QQQ", -0.35)
    
    if not target_contract:
        # Simulated execution selection (Standard Gate 1 fallback for mocked scenarios)
        target_contract = OptionsPosition(
            ticker="QQQ", option_type="PUT", strike=480.0, expiry="2026-06-15",
            contracts=1, notional_value=0.0, delta=-0.34, bid=1.15, ask=1.20
        )
        
    selected_contract_delta = target_contract.delta or -0.34
    selected_contract_dte = target_contract.dte
    selected_contract_otm_pct = 0.065 # Mocked for logging if not derived
    
    # 3. Check DTE for rolls (Priority 1)
    roll_occurred = False
    for pos in current_positions:
        if pos.dte <= 30:
            signal = f"DTE Roll: {pos.expiry} is at {pos.dte} days. Delta-Optimal Strike Selection (-0.35 tgt) via Gate 1."
            generated_orders.append(_submit_ptrh_order('SELL_PUT', pos.notional_value, signal, contract=pos)) # Sell current
            generated_orders.append(_submit_ptrh_order('BUY_PUT', pos.notional_value, signal, contract=target_contract))  # Buy next
            last_action = "ROLL"
            roll_occurred = True
    
    # 4. Check notional drift and auto-correct (Priority 2)
    if not roll_occurred: 
        is_under_hedged = drift < -0.05
        is_over_hedged = drift > 0.15
        
        if is_under_hedged or is_over_hedged:
            delta_notional = required_notional - actual_notional
            action = 'BUY_PUT' if delta_notional > 0 else 'SELL_PUT'
            signal = f"Drift Correction: actual {actual_pct:.2%} vs target {target_pct:.2%}. Delta-Optimal Strike Selected. Delta: ${abs(delta_notional):,.2f}"
            
            # If we are BUYING puts to increase coverage, we buy the target contract.
            # If we are SELLING puts to decrease coverage, we sell the EXISTING contracts (FIFO/LIFO logic).
            active_contract = target_contract if action == 'BUY_PUT' else (current_positions[0] if current_positions else target_contract)
            
            generated_orders.append(_submit_ptrh_order(action, abs(delta_notional), signal, contract=active_contract))
            last_action = "CORRECT_DRIFT"
    
    # 5. Prepare Status for Monitoring
    nearest_dte = min([p.dte for p in current_positions]) if current_positions else 0
    approx_multiplier = 1.0 + cam_inputs.regime_score 

    status = PTRHStatus(
        regime=str(cam_inputs.regime_score), 
        multiplier=approx_multiplier,
        target_notional_pct=target_pct,
        actual_notional_pct=actual_pct,
        coverage_drift_pct=drift * 100,
        nearest_expiry_dte=nearest_dte,
        last_roll_date=datetime.date.today().isoformat() if last_action == "ROLL" else "N/A",
        dual_risk_active=(dual_risk_override_pct is not None),
        dual_risk_standard_pct=dual_risk_override_pct if dual_risk_override_pct else 0.0,
        last_action=last_action,
        last_action_timestamp=datetime.datetime.now().isoformat() if last_action != "NONE" else "",
        alerts=alerts,
        generated_orders=generated_orders
    )
    
    # Addendum 6 Drift Logging
    # print(f"[PTRH] Calibration Log: Spot QQQ | Delta {selected_contract_delta} | OTM% {selected_contract_otm_pct:.2%} | DTE {selected_contract_dte} | Guardrail: Gate 1 (Standard)")
    
    return status

if __name__ == '__main__':
    print("ARMS PTRH Module Active (Simulation Mode)")
    
    # Simulate a RISK_ON scenario
    test_inputs = CamInputs(
        current_equity_pct=1.0,
        regime_score=0.25,
        fem_concentration_score=0.40,
        macro_stress_score=0.20,
        cdm_active_signals=0,
        nav=50_000_000
    )
    
    # Existing put at 35 DTE, correct sizing
    test_pos = [OptionsPosition("QQQ", "PUT", 400, "2026-05-05", 100, 600_000)]
    
    res = run_ptrh_module(test_inputs, test_pos)
    print(f"Status: {res}")
